"""
This file contains all the constants used in the project. 
"""

# file I/O
IMAGEFILEEXTENSION = "jpg"
MAXIMAGEWIDTH = 8192
MAXIMAGEHEIGHT = 8192
TIMEESTIMATIONCOUNTER = 5000
DATASETSCALINGFACTOR = 0.5

# data prep
FULLIMAGESIZE = 256
LOWIMAGESIZE = 64
NUMPARALLELCALLS = 8