"""
This file contains all the constants used in the project. 
"""

# general
USEGPU = True

# file I/O
DATAPATH = '../data/unlabeled2017/*'
IMAGEFILEEXTENSION = "jpg"
MAXIMAGEWIDTH = 8192
MAXIMAGEHEIGHT = 8192
TIMEESTIMATIONCOUNTER = 5000
DATASETSCALINGFACTOR = 0.5

# data prep
FULLIMAGESIZE = 128
LOWIMAGESIZE = 32
NUMCHANNELS = 3
NUMPARALLELCALLS = 8
TESTSPLITSIZE = 0.2
BATCHSIZE = 8
BUFFERSIZE = 16
PREFETCHSIZE = 32

# data augmentation
AUGMENTATIONPROBABILITY = 0.4
SATURATIONMIN = 0.8
SATURATIONMAX = 1.5
CONTRASTMAX = 0.9
CONTRASTMIN = 0.5
BRIGHTNESSMAXDETLA = 0.3

# training
EPOCHS = 50
WHEIGTSPATH = "run_%d_%m_%Y__%H-%M-%S"
CHECKPOINTINTERVAL = 5


# model
NUMRESBLOCKS = 16
